name: Publish to Docker Hub

on:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - main

jobs:
  publish-to-docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "BRANCH: ${BRANCH}"
          DOCKER_TAGS="${BRANCH},latest"
          echo "DOCKER_TAGS=${DOCKER_TAGS}" >> $GITHUB_ENV
      - name: Publish Docker Github Action
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: unfoldingword/loki_backup
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: ${{ env.DOCKER_TAGS }}